create database project;
use project;
# Healthcare Database 
SELECT* FROM HEALTHCARE;
-- 1. Retrieve the names of all patients in the database. 
SELECT NAME FROM HEALTHCARE;
-- 2. List the unique medical conditions present in the dataset.  
 SELECT DISTINCT MEDICAL_CONDITION FROM HEALTHCARE;
-- 3. Find the total number of doctors in the healthcare system.
 SELECT COUNT(DISTINCT DOCTOR) FROM HEALTHCARE;
-- 4. Retrieve the details of all female patients. 
 SELECT * FROM HEALTHCARE WHERE GENDER="FEMALE";
-- 5. what is the average age of patients in the database. 
SELECT AVG(Age) AS Average_Age
FROM healthcare;
-- 6. Identify the patients who have more than one medical condition.  
SELECT NAME,COUNT(DISTINCT MEDICAL_CONDITION) FROM HEALTHCARE 
GROUP BY NAME HAVING COUNT(DISTINCT MEDICAL_CONDITION)>1;
-- 7. List the names of all doctors.  
SELECT DISTINCT DOCTOR FROM HEALTHCARE;
-- 8.Identify the most common medical condition among patients. 
SELECT MEDICAL_CONDITION, COUNT(*) AS CONDITION_COUNT FROM HEALTHCARE 
GROUP BY MEDICAL_CONDITION ORDER BY CONDITION_COUNT DESC LIMIT 1;
-- 9.Find the patients who are older than 60 years and have diabetes.
  SELECT NAME FROM HEALTHCARE WHERE AGE>60 AND MEDICAL_CONDITION="DIABETES";
-- 10.Calculate the total revenue generated by the healthcare system. 
SELECT SUM(BILLING_AMOUNT)AS TOTAL_REVENUE FROM HEALTHCARE;
-- 11.Find the doctor with the oldest patient. 
SELECT DOCTOR,AGE FROM HEALTHCARE ORDER BY AGE DESC;
SELECT Doctor
FROM healthcare
WHERE Age = (SELECT MAX(Age) FROM healthcare);
-- 12.Calculate the average duration of medical visits. 
SELECT AVG(CAST(DURATION AS DOUBLE)) AS AVERAGE_DURATION FROM HEALTHCARE;
-- 13.Give the names of patients whose name starts with A. 
SELECT NAME FROM HEALTHCARE WHERE NAME LIKE "A%";
-- 14.How many male and female patients are there in dataset. 
  SELECT GENDER,COUNT(*) FROM HEALTHCARE  GROUP BY GENDER;
-- 15.how many patients are normal. 
SELECT COUNT(*) FROM HEALTHCARE WHERE TEST_RESULTS="NORMAL"; 
-- 16.how many patients are abnormal or Inconclusive.
 SELECT COUNT(*) FROM HEALTHCARE WHERE TEST_RESULTS IN ("INCONCLUSIVE","ABNORMAL");
 -- 17.how many patients of blood group AB+ are there of age above 52.  
  SELECT COUNT(*)FROM HEALTHCARE WHERE BLOOD_TYPE="AB+" AND AGE>52;
-- 18. how many patients have paid the bill above 24890.
 SELECT COUNT(*) FROM HEALTHCARE WHERE BILLING_AMOUNT>24890; 
 -- 19. what are the names of patients having Asthma. 
SELECT NAME FROM HEALTHCARE WHERE MEDICAL_CONDITION="ASTHMA";
-- 20. how many patients have cancer.  
SELECT COUNT(*) AS COUNT_PATIENT FROM HEALTHCARE WHERE MEDICAL_CONDITION="CANCER";
-- 21. what are the names and blood groups of patients admitted to room no. 292. 
  SELECT NAME,BLOOD_TYPE FROM HEALTHCARE WHERE ROOM_NUMBER=292;
-- 22. how many males have Arthritis. 
SELECT COUNT(*) AS MALE_ATHRITIS_COUNT FROM HEALTHCARE WHERE GENDER="MALE" AND MEDICAL_CONDITION="ARTHRITIS";
-- 23. How many patients were admitted to Harris and Sons hospital.
  SELECT COUNT(*) FROM HEALTHCARE WHERE HOSPITAL="HARRIS AND SONS";
-- 24. what are the names of patients whose Insurance Provider are Cigna.  
  SELECT NAME FROM HEALTHCARE WHERE INSURANCE_PROVIDER="CIGNA";
-- 25. Name the Medical Condition having patients whose ages is greater than average age.
SELECT DISTINCT MEDICAL_CONDITION FROM HEALTHCARE WHERE AGE>(SELECT AVG(AGE) FROM HEALTHCARE);
